### ISSUE TITLE
Installation under Laravel 8

### ISSUE THREAD

**Issue by rickavmaniac** [timothydc/laravel-lightspeed-retail-api#15]
Hi,

I try a new install (composer require timothydc/laravel-lightspeed-retail-api
) under a Laravel 8 projet. But I got this error:

"Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - timothydc/laravel-lightspeed-retail-api v0.12-alpha requires guzzlehttp/guzzle ^6.5 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Installation request for timothydc/laravel-lightspeed-retail-api ^0.12.0@alpha -> satisfiable by timothydc/laravel-lightspeed-retail-api[v0.12-alpha].
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0]."

Any idea?

**Comment by timothydc** [comment]
I haven't gotten around to upgrading this package to L8 yet. I'll try to make some time this week!

**Comment by timothydc** [comment]
Merged
