### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by rickavmaniac** [timothydc/laravel-lightspeed-retail-api#7]
Hi,

Sorry I am new to Laravel so maybe it is just me but I got this error when installing the package :
$ composer require timothydc/laravel-lightspeed-retail-api
 
[InvalidArgumentException]                                                                                                                                                    
  Could not find a version of package timothydc/laravel-lightspeed-retail-api matching your minimum-stability (stable). Require it with an explicit version constraint allowin  
  g its desired stability.   

Anything I can do to by pass this?

**Comment by timothydc** [comment]
At the moment there is no stable version of this package.
To what [minimum version setting](https://getcomposer.org/doc/04-schema.md#minimum-stability) is your `composer.json` set? It should be atleast `"minimum-stability": "alpha"`

**Comment by rickavmaniac** [comment]
Ok now everything work. Wow nice job !

I already get my token and do some basic query with the Item and category ressource. 

For now everything work great and I must say you did a pretty good job... Congrats!

I think right now ressources are only read only? Did you plan to allow ressource create/update in the future?

I plan to use this module in my company and if we do so, I would like to make a contribution to you. You will save us many many hours of dev time...

Keep the good work !

**Comment by timothydc** [comment]
You can create and update resources too! For example, if you'd like to update a category:
`LightspeedRetailApi::api()->category()->update(123, ['name' => 'foobar']);`

At the moment there aren't many LS retail resources availabable, but you can always directly call them.
For example if you'd like to call the above API call directly: 
`LightspeedRetailApi::api()->put('Category', 123, ['name' => 'foobar']);` Mind the capitalization of `Category`.

All resources in [the documentation](https://developers.lightspeedhq.com/retail/introduction/introduction/) are supported.

**Comment by rickavmaniac** [comment]
Great ! With the direct access ex. get('Sale') I am able to read all my ressources... cool :-)

I even create a new entry with a post and it work well.

Also, was wondering if It is possible to do a search other than by id? ex. all item with a catagoryID = 180 ?

Something like that : LightspeedRetailApi::api()->Item()->where('categoryID', 180)->get());

Last but not least, LightSpeed limit the number of returns to 100 items pers requests. What we do if we need all the items in ressource? We do a loop? But I think LightSpeed have a max numbers of requests so a pause (or multiples pause) will be needed somewhere during those request?


Keep the good work...

**Comment by timothydc** [comment]
I [updated the readme](https://github.com/timothydc/laravel-lightspeed-retail-api#make-api-calls) with some information on how to use query parameters. Please update your installation.

But try and open a new issue when asking additional questions!
