### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by rickavmaniac** [timothydc/laravel-lightspeed-retail-api#9]
Hi,

Everything was loading fine until I try to make an artisan command (php artisan make:command) to run my sync code.

My code is working but as soon as I call one of your class, I get an error. (Same code  that run inside my app is ok)

When any API class in an artisan command I get this error 
"
syntax error, unexpected 'ApiClient' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)

  at vendor/timothydc/laravel-lightspeed-retail-api/src/LightspeedRetailApi.php:10
     6| use TimothyDC\LightspeedRetailApi\Services\ApiClient;
     7| 
     8| class LightspeedRetailApi
     9| {
  > 10|     private ApiClient $apiClient;
    11| 
    12|     public function __construct(ApiClient $apiClient)
    13|     {
    14|         $this->apiClient = $apiClient;

      +1 vendor frames 
  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("TimothyDC\LightspeedRetailApi\LightspeedRetailApi")

      +10 vendor frames 
  13  app/StockSync.php:155
      Illuminate\Support\Facades\Facade::__callStatic("api", [])
"

At first I was thinking it is the .env variables that was not loading but I did a dump(env(PRESTASHOP_WS_KEY)) and the value is ok.

Any ideas ?

**Comment by timothydc** [comment]
Could you post your complete `LightspeedRetailApi` class please?

**Comment by rickavmaniac** [comment]
> Could you post your complete `LightspeedRetailApi` class please?

The LightspeedRetailAPI is your class.

Here the line of code that consume it : 

$items = LightspeedRetailApi::api()->Item()->get(null, ['load_relations' => 'all', 'offset' => 0]);

This line work when calling from controller but not when calling from php artisan command line (see post no1 for return error)

**Comment by timothydc** [comment]
What PHP version are you running on the CLI?

**Comment by rickavmaniac** [comment]
BINGO ! That was it.

In my console for an unknown reason I run on 7.3 and 7.4 in Laravel. I change to 7.4 in console and now everything is fine.

Many thanks!
